/// Material Icons Unicode 码点常量列表
///
/// 用于图标选择器显示。前端只维护码点列表，不维护 IconData 映射。
/// 后端返回 Unicode 码点，前端通过 DynamicIcon 直接渲染。
///
/// 数据来源：https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints
library;

/// 图标数据模型
class IconUnicode {
  final String code;      // Unicode 码点（16进制，如 "e56c"）
  final String name;      // 图标名称（用于显示，如 "restaurant"）
  final String category;  // 图标分类（如 "餐饮"）

  const IconUnicode({
    required this.code,
    required this.name,
    required this.category,
  });

  /// 转换为 Map（用于 GridView）
  Map<String, dynamic> toMap() {
    return {
      'code': code,
      'name': name,
    };
  }
}

/// 所有可用的图标 Unicode 码点列表
const List<IconUnicode> materialIconsUnicode = [
  // ===== 餐饮类 =====
  IconUnicode(code: 'e56c', name: 'restaurant', category: '餐饮'),
  IconUnicode(code: 'eb44', name: 'free_breakfast', category: '餐饮'),
  IconUnicode(code: 'ea54', name: 'breakfast_dining', category: '餐饮'),
  IconUnicode(code: 'ea61', name: 'lunch_dining', category: '餐饮'),
  IconUnicode(code: 'ea57', name: 'dinner_dining', category: '餐饮'),
  IconUnicode(code: 'eaac', name: 'cookie', category: '餐饮'),
  IconUnicode(code: 'e541', name: 'local_cafe', category: '餐饮'),
  IconUnicode(code: 'e540', name: 'local_bar', category: '餐饮'),
  IconUnicode(code: 'e7e9', name: 'cake', category: '餐饮'),
  IconUnicode(code: 'ea69', name: 'icecream', category: '餐饮'),
  IconUnicode(code: 'ea64', name: 'ramen_dining', category: '餐饮'),
  IconUnicode(code: 'f1ea', name: 'set_meal', category: '餐饮'),

  // ===== 交通类 =====
  IconUnicode(code: 'e531', name: 'directions_car', category: '交通'),
  IconUnicode(code: 'e530', name: 'directions_bus', category: '交通'),
  IconUnicode(code: 'e535', name: 'directions_transit', category: '交通'),
  IconUnicode(code: 'e52f', name: 'directions_bike', category: '交通'),
  IconUnicode(code: 'e559', name: 'local_taxi', category: '交通'),
  IconUnicode(code: 'e539', name: 'flight', category: '交通'),
  IconUnicode(code: 'e570', name: 'train', category: '交通'),
  IconUnicode(code: 'e558', name: 'local_shipping', category: '交通'),
  IconUnicode(code: 'e9f9', name: 'two_wheeler', category: '交通'),
  IconUnicode(code: 'eb1d', name: 'electric_moped', category: '交通'),
  IconUnicode(code: 'eb29', name: 'pedal_bike', category: '交通'),
  IconUnicode(code: 'eb3c', name: 'airport_shuttle', category: '交通'),

  // ===== 购物类 =====
  IconUnicode(code: 'e8cc', name: 'shopping_cart', category: '购物'),
  IconUnicode(code: 'e8cb', name: 'shopping_basket', category: '购物'),
  IconUnicode(code: 'f19e', name: 'checkroom', category: '购物'),
  IconUnicode(code: 'e1b1', name: 'devices', category: '购物'),
  IconUnicode(code: 'e16b', name: 'weekend', category: '购物'),  // 家居用品
  IconUnicode(code: 'e87c', name: 'face', category: '购物'),
  IconUnicode(code: 'f1cc', name: 'shopping_bag', category: '购物'),
  IconUnicode(code: 'e8d1', name: 'store', category: '购物'),
  IconUnicode(code: 'ea12', name: 'storefront', category: '购物'),
  IconUnicode(code: 'e54c', name: 'local_mall', category: '购物'),

  // ===== 居住类 =====
  IconUnicode(code: 'e88a', name: 'home', category: '居住'),
  IconUnicode(code: 'ea40', name: 'apartment', category: '居住'),
  IconUnicode(code: 'e798', name: 'water_drop', category: '居住'),
  IconUnicode(code: 'e8d3', name: 'receipt_long', category: '居住'),
  IconUnicode(code: 'e1e2', name: 'wifi', category: '居住'),
  IconUnicode(code: 'f10b', name: 'handyman', category: '居住'),
  IconUnicode(code: 'e53a', name: 'hotel', category: '居住'),
  IconUnicode(code: 'ea09', name: 'home_work', category: '居住'),
  IconUnicode(code: 'e8a6', name: 'door_front', category: '居住'),
  IconUnicode(code: 'e6cf', name: 'meeting_room', category: '居住'),
  IconUnicode(code: 'f236', name: 'balcony', category: '居住'),
  IconUnicode(code: 'efc1', name: 'garage_home', category: '居住'),

  // ===== 娱乐类 =====
  IconUnicode(code: 'e02c', name: 'movie', category: '娱乐'),
  IconUnicode(code: 'ea28', name: 'sports_esports', category: '娱乐'),
  IconUnicode(code: 'e029', name: 'mic', category: '娱乐'),
  IconUnicode(code: 'ea26', name: 'sports_basketball', category: '娱乐'),
  IconUnicode(code: 'e407', name: 'landscape', category: '娱乐'),
  IconUnicode(code: 'e43a', name: 'movie_filter', category: '娱乐'),
  IconUnicode(code: 'e405', name: 'music_note', category: '娱乐'),
  IconUnicode(code: 'ea66', name: 'theater_comedy', category: '娱乐'),
  IconUnicode(code: 'eb40', name: 'casino', category: '娱乐'),
  IconUnicode(code: 'f01f', name: 'headphones', category: '娱乐'),
  IconUnicode(code: 'e338', name: 'videogame_asset', category: '娱乐'),

  // ===== 医疗类 =====
  IconUnicode(code: 'e548', name: 'local_hospital', category: '医疗'),
  IconUnicode(code: 'f033', name: 'medication', category: '医疗'),
  IconUnicode(code: 'e85d', name: 'assignment', category: '医疗'),
  IconUnicode(code: 'f109', name: 'medical_services', category: '医疗'),
  IconUnicode(code: 'eb4c', name: 'spa', category: '医疗'),  // 保健品
  IconUnicode(code: 'e1d5', name: 'health_and_safety', category: '医疗'),  // 保险
  IconUnicode(code: 'e3f3', name: 'healing', category: '医疗'),
  IconUnicode(code: 'f221', name: 'coronavirus', category: '医疗'),

  // ===== 教育类 =====
  IconUnicode(code: 'e80c', name: 'school', category: '教育'),
  IconUnicode(code: 'e84f', name: 'account_balance', category: '教育'),
  IconUnicode(code: 'ea19', name: 'menu_book', category: '教育'),
  IconUnicode(code: 'efec', name: 'cast_for_education', category: '教育'),
  IconUnicode(code: 'e30a', name: 'computer', category: '教育'),
  IconUnicode(code: 'f04c', name: 'quiz', category: '教育'),
  IconUnicode(code: 'ea4b', name: 'science', category: '教育'),
  IconUnicode(code: 'ea5f', name: 'calculate', category: '教育'),
  IconUnicode(code: 'ea4a', name: 'psychology', category: '教育'),
  IconUnicode(code: 'e666', name: 'auto_stories', category: '教育'),
  IconUnicode(code: 'e02f', name: 'library_books', category: '教育'),

  // ===== 通讯类 =====
  IconUnicode(code: 'e0cd', name: 'phone', category: '通讯'),
  IconUnicode(code: 'e325', name: 'phone_iphone', category: '通讯'),
  IconUnicode(code: 'e640', name: 'network_check', category: '通讯'),
  IconUnicode(code: 'e328', name: 'router', category: '通讯'),
  IconUnicode(code: 'e554', name: 'local_post_office', category: '通讯'),
  IconUnicode(code: 'e0be', name: 'email', category: '通讯'),
  IconUnicode(code: 'e0ca', name: 'chat', category: '通讯'),
  IconUnicode(code: 'f8f9', name: 'broadcast_on_personal', category: '通讯'),
  IconUnicode(code: 'e163', name: 'send', category: '通讯'),
  IconUnicode(code: 'e18c', name: 'mark_email_read', category: '通讯'),

  // ===== 金融/工资类 =====
  IconUnicode(code: 'ef63', name: 'payments', category: '金融'),
  IconUnicode(code: 'e227', name: 'attach_money', category: '金融'),
  IconUnicode(code: 'e8e5', name: 'trending_up', category: '金融'),
  IconUnicode(code: 'e850', name: 'account_balance_wallet', category: '金融'),
  IconUnicode(code: 'e8d0', name: 'stars', category: '金融'),
  IconUnicode(code: 'ea23', name: 'emoji_events', category: '金融'),
  IconUnicode(code: 'e6e1', name: 'show_chart', category: '金融'),
  IconUnicode(code: 'e2eb', name: 'savings', category: '金融'),
  IconUnicode(code: 'ebc5', name: 'currency_bitcoin', category: '金融'),
  IconUnicode(code: 'e870', name: 'credit_card', category: '金融'),
  IconUnicode(code: 'eb70', name: 'currency_exchange', category: '金融'),

  // ===== 工作类 =====
  IconUnicode(code: 'e8f9', name: 'work', category: '工作'),
  IconUnicode(code: 'f0e2', name: 'support_agent', category: '工作'),

  // ===== 礼物/人情 =====
  IconUnicode(code: 'e8f6', name: 'card_giftcard', category: '人情'),
  IconUnicode(code: 'e8b1', name: 'redeem', category: '人情'),
  IconUnicode(code: 'e87d', name: 'favorite', category: '人情'),
  IconUnicode(code: 'ea65', name: 'celebration', category: '人情'),
  IconUnicode(code: 'e8dc', name: 'card_giftcard', category: '人情'),
  IconUnicode(code: 'e25a', name: 'volunteer_activism', category: '人情'),

  // ===== 其他 =====
  IconUnicode(code: 'e574', name: 'category', category: '其他'),
  IconUnicode(code: 'f0ff', name: 'volunteer_activism', category: '其他'),
  IconUnicode(code: 'eb91', name: 'child_care', category: '其他'),
  IconUnicode(code: 'e91d', name: 'pets', category: '其他'),
  IconUnicode(code: 'eb43', name: 'fitness_center', category: '其他'),
  IconUnicode(code: 'f0ff', name: 'cleaning_services', category: '其他'),
  IconUnicode(code: 'e54b', name: 'local_laundry_service', category: '其他'),
  IconUnicode(code: 'f1b3', name: 'iron', category: '其他'),
  IconUnicode(code: 'ef6e', name: 'receipt_long', category: '其他'),
  IconUnicode(code: 'ea53', name: 'bakery_dining', category: '其他'),
  IconUnicode(code: 'f1e9', name: 'tapas', category: '其他'),
  IconUnicode(code: 'eb47', name: 'kitchen', category: '其他'),

  // ===== 运动健康 =====
  IconUnicode(code: 'eb43', name: 'fitness_center', category: '运动'),
  IconUnicode(code: 'e601', name: 'directions_run', category: '运动'),
  IconUnicode(code: 'e602', name: 'directions_walk', category: '运动'),
  IconUnicode(code: 'ea66', name: 'sports_basketball', category: '运动'),
  IconUnicode(code: 'ea68', name: 'sports_soccer', category: '运动'),
  IconUnicode(code: 'ea67', name: 'sports_baseball', category: '运动'),
  IconUnicode(code: 'ea6a', name: 'sports_tennis', category: '运动'),
  IconUnicode(code: 'e3f3', name: 'healing', category: '运动'),
  IconUnicode(code: 'e54e', name: 'pool', category: '运动'),
  IconUnicode(code: 'e508', name: 'golf_course', category: '运动'),
  IconUnicode(code: 'e564', name: 'downhill_skiing', category: '运动'),
  IconUnicode(code: 'f1c6', name: 'sports_mma', category: '运动'),
  IconUnicode(code: 'ea6b', name: 'sports_cricket', category: '运动'),

  // ===== 办公/商务 =====
  IconUnicode(code: 'e873', name: 'description', category: '办公'),
  IconUnicode(code: 'e85d', name: 'assignment', category: '办公'),
  IconUnicode(code: 'e8d5', name: 'assignment_ind', category: '办公'),
  IconUnicode(code: 'e8d6', name: 'assignment_turned_in', category: '办公'),
  IconUnicode(code: 'e8d4', name: 'assignment_return', category: '办公'),
  IconUnicode(code: 'e25a', name: 'work', category: '办公'),
  IconUnicode(code: 'e8f9', name: 'work_outline', category: '办公'),
  IconUnicode(code: 'f1bc', name: 'business_center', category: '办公'),
  IconUnicode(code: 'e0e0', name: 'domain', category: '办公'),
  IconUnicode(code: 'e84f', name: 'account_balance', category: '办公'),
  IconUnicode(code: 'e80d', name: 'attach_file', category: '办公'),
  IconUnicode(code: 'e158', name: 'folder', category: '办公'),
  IconUnicode(code: 'e158', name: 'folder_open', category: '办公'),
  IconUnicode(code: 'e86d', name: 'print', category: '办公'),
  IconUnicode(code: 'e8ad', name: 'scanner', category: '办公'),

  // ===== 时间/日历 =====
  IconUnicode(code: 'e916', name: 'access_time', category: '时间'),
  IconUnicode(code: 'e919', name: 'schedule', category: '时间'),
  IconUnicode(code: 'e922', name: 'event', category: '时间'),
  IconUnicode(code: 'e923', name: 'event_available', category: '时间'),
  IconUnicode(code: 'e924', name: 'event_busy', category: '时间'),
  IconUnicode(code: 'e925', name: 'event_note', category: '时间'),
  IconUnicode(code: 'e615', name: 'today', category: '时间'),
  IconUnicode(code: 'e616', name: 'date_range', category: '时间'),
  IconUnicode(code: 'e617', name: 'update', category: '时间'),
  IconUnicode(code: 'e618', name: 'alarm', category: '时间'),
  IconUnicode(code: 'e619', name: 'timer', category: '时间'),
  IconUnicode(code: 'e61a', name: 'access_alarms', category: '时间'),
  IconUnicode(code: 'e61b', name: 'watch_later', category: '时间'),

  // ===== 天气/环境 =====
  IconUnicode(code: 'e42a', name: 'wb_sunny', category: '天气'),
  IconUnicode(code: 'e42b', name: 'wb_cloudy', category: '天气'),
  IconUnicode(code: 'e42c', name: 'wb_twighlight', category: '天气'),
  IconUnicode(code: 'e42d', name: 'ac_unit', category: '天气'),
  IconUnicode(code: 'e42e', name: 'whatshot', category: '天气'),
  IconUnicode(code: 'e42f', name: 'severe_cold', category: '天气'),
  IconUnicode(code: 'e430', name: 'thunderstorm', category: '天气'),
  IconUnicode(code: 'e431', name: 'water_drop', category: '天气'),
  IconUnicode(code: 'e432', name: 'air', category: '天气'),
  IconUnicode(code: 'e433', name: 'beach_access', category: '天气'),
  IconUnicode(code: 'e434', name: 'nature', category: '天气'),
  IconUnicode(code: 'e435', name: 'nature_people', category: '天气'),
  IconUnicode(code: 'e436', name: 'terrain', category: '天气'),
  IconUnicode(code: 'e437', name: 'forest', category: '天气'),

  // ├── 添加更多常用图标 ├──
  IconUnicode(code: 'e145', name: 'star', category: '常用'),
  IconUnicode(code: 'e146', name: 'star_border', category: '常用'),
  IconUnicode(code: 'e147', name: 'star_half', category: '常用'),
  IconUnicode(code: 'e838', name: 'thumb_up', category: '常用'),
  IconUnicode(code: 'e839', name: 'thumb_down', category: '常用'),
  IconUnicode(code: 'e83a', name: 'bookmark', category: '常用'),
  IconUnicode(code: 'e83b', name: 'bookmark_border', category: '常用'),
  IconUnicode(code: 'e83c', name: 'label', category: '常用'),
  IconUnicode(code: 'e83d', name: 'label_outline', category: '常用'),
  IconUnicode(code: 'e83e', name: 'tag', category: '常用'),
  IconUnicode(code: 'e83f', name: 'label_important', category: '常用'),
  IconUnicode(code: 'e0a4', name: 'info', category: '常用'),
  IconUnicode(code: 'e0a5', name: 'info_outline', category: '常用'),
  IconUnicode(code: 'e0a6', name: 'warning', category: '常用'),
  IconUnicode(code: 'e0a7', name: 'error', category: '常用'),
  IconUnicode(code: 'e0a8', name: 'error_outline', category: '常用'),
  IconUnicode(code: 'e0a9', name: 'check_circle', category: '常用'),
  IconUnicode(code: 'e0aa', name: 'check_circle_outline', category: '常用'),
  IconUnicode(code: 'e0ab', name: 'cancel', category: '常用'),
  IconUnicode(code: 'e0ac', name: 'add_circle', category: '常用'),
  IconUnicode(code: 'e0ad', name: 'add_circle_outline', category: '常用'),
  IconUnicode(code: 'e0ae', name: 'remove_circle', category: '常用'),
  IconUnicode(code: 'e0af', name: 'remove_circle_outline', category: '常用'),
  IconUnicode(code: 'e5c3', name: 'add', category: '常用'),
  IconUnicode(code: 'e5c4', name: 'add_box', category: '常用'),
  IconUnicode(code: 'e5c5', name: 'remove', category: '常用'),
  IconUnicode(code: 'e5c6', name: 'delete', category: '常用'),
  IconUnicode(code: 'e5c7', name: 'clear', category: '常用'),
  IconUnicode(code: 'e5c8', name: 'check', category: '常用'),
  IconUnicode(code: 'e5c9', name: 'close', category: '常用'),
  IconUnicode(code: 'e5ca', name: 'expand_less', category: '常用'),
  IconUnicode(code: 'e5cb', name: 'expand_more', category: '常用'),
  IconUnicode(code: 'e5cc', name: 'arrow_back', category: '常用'),
  IconUnicode(code: 'e5cd', name: 'arrow_forward', category: '常用'),
  IconUnicode(code: 'e5ce', name: 'arrow_upward', category: '常用'),
  IconUnicode(code: 'e5cf', name: 'arrow_downward', category: '常用'),
  IconUnicode(code: 'e5d0', name: 'chevron_left', category: '常用'),
  IconUnicode(code: 'e5d1', name: 'chevron_right', category: '常用'),
  IconUnicode(code: 'e5d2', name: 'chevron_up', category: '常用'),
  IconUnicode(code: 'e5d3', name: 'chevron_down', category: '常用'),
  IconUnicode(code: 'e5d4', name: 'arrow_back_ios', category: '常用'),
  IconUnicode(code: 'e5d5', name: 'arrow_forward_ios', category: '常用'),
  IconUnicode(code: 'e5d6', name: 'first_page', category: '常用'),
  IconUnicode(code: 'e5d7', name: 'last_page', category: '常用'),
  IconUnicode(code: 'e5d8', name: 'keyboard_arrow_left', category: '常用'),
  IconUnicode(code: 'e5d9', name: 'keyboard_arrow_right', category: '常用'),
  IconUnicode(code: 'e5da', name: 'keyboard_arrow_up', category: '常用'),
  IconUnicode(code: 'e5db', name: 'keyboard_arrow_down', category: '常用'),
  IconUnicode(code: 'e5dc', name: 'menu', category: '常用'),
  IconUnicode(code: 'e5dd', name: 'more_vert', category: '常用'),
  IconUnicode(code: 'e5de', name: 'more_horiz', category: '常用'),
  IconUnicode(code: 'e5df', name: 'settings', category: '常用'),
  IconUnicode(code: 'e5e0', name: 'search', category: '常用'),
  IconUnicode(code: 'e5e1', name: 'visibility', category: '常用'),
  IconUnicode(code: 'e5e2', name: 'visibility_off', category: '常用'),
  IconUnicode(code: 'e5e3', name: 'lock', category: '常用'),
  IconUnicode(code: 'e5e4', name: 'lock_open', category: '常用'),
  IconUnicode(code: 'e5e5', name: 'edit', category: '常用'),
  IconUnicode(code: 'e5e6', name: 'delete_outline', category: '常用'),
  IconUnicode(code: 'e5e7', name: 'content_copy', category: '常用'),
  IconUnicode(code: 'e5e8', name: 'content_cut', category: '常用'),
  IconUnicode(code: 'e5e9', name: 'content_paste', category: '常用'),
  IconUnicode(code: 'e5ea', name: 'drafts', category: '常用'),
  IconUnicode(code: 'e5eb', name: 'inbox', category: '常用'),
  IconUnicode(code: 'e5ec', name: 'mail', category: '常用'),
  IconUnicode(code: 'e5ed', name: 'mark_email_read', category: '常用'),
  IconUnicode(code: 'e5ee', name: 'mark_email_unread', category: '常用'),
  IconUnicode(code: 'e5ef', name: 'notifications', category: '常用'),
  IconUnicode(code: 'e5f0', name: 'notifications_active', category: '常用'),
  IconUnicode(code: 'e5f1', name: 'notifications_none', category: '常用'),
  IconUnicode(code: 'e5f2', name: 'notifications_off', category: '常用'),
  IconUnicode(code: 'e5f3', name: 'notifications_paused', category: '常用'),
  IconUnicode(code: 'e8b0', name: 'person', category: '常用'),
  IconUnicode(code: 'e8b1', name: 'person_outline', category: '常用'),
  IconUnicode(code: 'e8b2', name: 'people', category: '常用'),
  IconUnicode(code: 'e8b3', name: 'people_outline', category: '常用'),
  IconUnicode(code: 'e8b4', name: 'group', category: '常用'),
  IconUnicode(code: 'e8b5', name: 'group_add', category: '常用'),
  IconUnicode(code: 'e8b6', name: 'person_add', category: '常用'),
  IconUnicode(code: 'e8b7', name: 'person_remove', category: '常用'),
  IconUnicode(code: 'e8b8', name: 'supervisor_account', category: '常用'),
  IconUnicode(code: 'e8b9', name: 'account_circle', category: '常用'),
  IconUnicode(code: 'e8ba', name: 'settings_applications', category: '常用'),
  IconUnicode(code: 'e8bb', name: 'settings_bluetooth', category: '常用'),
  IconUnicode(code: 'e8bc', name: 'settings_ethernet', category: '常用'),
  IconUnicode(code: 'e8bd', name: 'settings_input_antenna', category: '常用'),
  IconUnicode(code: 'e8be', name: 'settings_input_component', category: '常用'),
  IconUnicode(code: 'e8bf', name: 'settings_input_composite', category: '常用'),
  IconUnicode(code: 'e8c0', name: 'settings_input_hdmi', category: '常用'),
  IconUnicode(code: 'e8c1', name: 'settings_input_svideo', category: '常用'),
  IconUnicode(code: 'e8c2', name: 'settings_overscan', category: '常用'),
  IconUnicode(code: 'e8c3', name: 'settings_remote', category: '常用'),
  IconUnicode(code: 'e8c4', name: 'settings_system_daydream', category: '常用'),
  IconUnicode(code: 'e8c5', name: 'settings_voice', category: '常用'),
  IconUnicode(code: 'e8c6', name: 'help', category: '常用'),
  IconUnicode(code: 'e8c7', name: 'help_outline', category: '常用'),
  IconUnicode(code: 'e8c8', name: 'question_answer', category: '常用'),
  IconUnicode(code: 'e8c9', name: 'contact_support', category: '常用'),
  IconUnicode(code: 'e8ca', name: 'contact_page', category: '常用'),
  IconUnicode(code: 'e8cb', name: 'contacts', category: '常用'),
  IconUnicode(code: 'e8cc', name: 'dialer_sip', category: '常用'),
  IconUnicode(code: 'e8cd', name: 'dialpad', category: '常用'),
  IconUnicode(code: 'e8ce', name: 'import_contacts', category: '常用'),
  IconUnicode(code: 'e8cf', name: 'export_contacts', category: '常用'),
  IconUnicode(code: 'e8d0', name: 'import_export', category: '常用'),
  IconUnicode(code: 'e8d1', name: 'swap_horiz', category: '常用'),
  IconUnicode(code: 'e8d2', name: 'swap_vert', category: '常用'),
  IconUnicode(code: 'e8d3', name: 'swap_calls', category: '常用'),
  IconUnicode(code: 'e8d4', name: 'screen_share', category: '常用'),
  IconUnicode(code: 'e8d5', name: 'stop_screen_share', category: '常用'),
  IconUnicode(code: 'e8d6', name: 'call', category: '常用'),
  IconUnicode(code: 'e8d7', name: 'call_end', category: '常用'),
  IconUnicode(code: 'e8d8', name: 'call_made', category: '常用'),
  IconUnicode(code: 'e8d9', name: 'call_merge', category: '常用'),
  IconUnicode(code: 'e8da', name: 'call_missed', category: '常用'),
  IconUnicode(code: 'e8db', name: 'call_received', category: '常用'),
  IconUnicode(code: 'e8dc', name: 'call_split', category: '常用'),
  IconUnicode(code: 'e8dd', name: 'chat_bubble', category: '常用'),
  IconUnicode(code: 'e8de', name: 'chat_bubble_outline', category: '常用'),
  IconUnicode(code: 'e8df', name: 'chat', category: '常用'),
  IconUnicode(code: 'e8e0', name: 'chat_outline', category: '常用'),
  IconUnicode(code: 'e8e1', name: 'forum', category: '常用'),
  IconUnicode(code: 'e8e2', name: 'history', category: '常用'),
  IconUnicode(code: 'e8e3', name: 'history_edu', category: '常用'),
  IconUnicode(code: 'e8e4', name: 'lightbulb', category: '常用'),
  IconUnicode(code: 'e8e5', name: 'lightbulb_outline', category: '常用'),
  IconUnicode(code: 'e8e6', name: 'tip', category: '常用'),
  IconUnicode(code: 'e8e7', name: 'tips_and_updates', category: '常用'),
  IconUnicode(code: 'e8e8', name: 'auto_awesome', category: '常用'),
  IconUnicode(code: 'e8e9', name: 'auto_awesome_mosaic', category: '常用'),
  IconUnicode(code: 'e8ea', name: 'auto_awesome_outline', category: '常用'),
  IconUnicode(code: 'e8eb', name: 'verified', category: '常用'),
  IconUnicode(code: 'e8ec', name: 'verified_user', category: '常用'),
  IconUnicode(code: 'e8ed', name: 'security', category: '常用'),
  IconUnicode(code: 'e8ee', name: 'lock_clock', category: '常用'),
  IconUnicode(code: 'e8ef', name: 'admin_panel_settings', category: '常用'),
  IconUnicode(code: 'e8f0', name: 'privacy_tip', category: '常用'),
  IconUnicode(code: 'e8f1', name: 'gavel', category: '常用'),
  IconUnicode(code: 'e8f2', name: 'policy', category: '常用'),
  IconUnicode(code: 'e8f3', name: 'report', category: '常用'),
  IconUnicode(code: 'e8f4', name: 'flag', category: '常用'),
  IconUnicode(code: 'e8f5', name: 'outline_flag', category: '常用'),
  IconUnicode(code: 'e8f6', name: 'report_problem', category: '常用'),
  IconUnicode(code: 'e8f7', name: 'bug_report', category: '常用'),
  IconUnicode(code: 'e8f8', name: 'build', category: '常用'),
  IconUnicode(code: 'e8f9', name: 'construction', category: '常用'),
  IconUnicode(code: 'e8fa', name: 'handyman', category: '常用'),
  IconUnicode(code: 'e8fb', name: 'design_services', category: '常用'),
  IconUnicode(code: 'e8fc', name: 'home_repair_service', category: '常用'),
  IconUnicode(code: 'e8fd', name: 'maintenance', category: '常用'),
  IconUnicode(code: 'e8fe', name: 'format_paint', category: '常用'),
  IconUnicode(code: 'e8ff', name: 'palette', category: '常用'),
  IconUnicode(code: 'e900', name: 'brush', category: '常用'),
  IconUnicode(code: 'e901', name: 'color_lens', category: '常用'),
  IconUnicode(code: 'e902', name: 'invert_colors', category: '常用'),
  IconUnicode(code: 'e903', name: 'invert_colors_off', category: '常用'),
  IconUnicode(code: 'e904', name: 'gradient', category: '常用'),
  IconUnicode(code: 'e905', name: 'colorize', category: '常用'),
  IconUnicode(code: 'e906', name: 'style', category: '常用'),
  IconUnicode(code: 'e907', name: 'sort', category: '常用'),
  IconUnicode(code: 'e908', name: 'sort_by_alpha', category: '常用'),
  IconUnicode(code: 'e909', name: 'shuffle', category: '常用'),
  IconUnicode(code: 'e90a', name: 'shuffle_on', category: '常用'),
  IconUnicode(code: 'e90b', name: 'compare_arrows', category: '常用'),
  IconUnicode(code: 'e90c', name: 'compare', category: '常用'),
  IconUnicode(code: 'e90d', name: 'sync', category: '常用'),
  IconUnicode(code: 'e90e', name: 'sync_alt', category: '常用'),
  IconUnicode(code: 'e90f', name: 'sync_disabled', category: '常用'),
  IconUnicode(code: 'e910', name: 'sync_problem', category: '常用'),
  IconUnicode(code: 'e911', name: 'refresh', category: '常用'),
  IconUnicode(code: 'e912', name: 'refresh_off', category: '常用'),
  IconUnicode(code: 'e913', name: 'repeat', category: '常用'),
  IconUnicode(code: 'e914', name: 'repeat_on', category: '常用'),
  IconUnicode(code: 'e915', name: 'replay', category: '常用'),
  IconUnicode(code: 'e916', name: 'replay_circle_filled', category: '常用'),
  IconUnicode(code: 'e917', name: 'update', category: '常用'),
  IconUnicode(code: 'e918', name: 'system_update', category: '常用'),
  IconUnicode(code: 'e919', name: 'system_update_alt', category: '常用'),
];

/// 获取所有图标码点（用于图标选择器）
List<Map<String, dynamic>> getAllIconCodes() {
  return materialIconsUnicode.map((icon) => icon.toMap()).toList();
}
