-- 添加 config_id 字段用于匹配配置文件中的系统分类
ALTER TABLE categories ADD COLUMN config_id INTEGER;
CREATE INDEX idx_category_config_id ON categories(config_id);

-- 为现有的系统分类填充 config_id（根据名称匹配）
-- 注意：这个步骤只需要执行一次，之后新创建的分类会自动设置 config_id
UPDATE categories SET config_id = 1 WHERE name = '餐饮' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 101 WHERE name = '早餐' AND is_system = true;
UPDATE categories SET config_id = 102 WHERE name = '午餐' AND is_system = true;
UPDATE categories SET config_id = 103 WHERE name = '晚餐' AND is_system = true;
UPDATE categories SET config_id = 104 WHERE name = '零食' AND is_system = true;
UPDATE categories SET config_id = 105 WHERE name = '饮料' AND is_system = true;
UPDATE categories SET config_id = 2 WHERE name = '交通' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 201 WHERE name = '公交地铁' AND is_system = true;
UPDATE categories SET config_id = 202 WHERE name = '打车' AND is_system = true;
UPDATE categories SET config_id = 203 WHERE name = '私家车' AND is_system = true;
UPDATE categories SET config_id = 204 WHERE name = '火车飞机' AND is_system = true;
UPDATE categories SET config_id = 205 WHERE name = '共享单车' AND is_system = true;
UPDATE categories SET config_id = 3 WHERE name = '购物' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 301 WHERE name = '日用品' AND is_system = true;
UPDATE categories SET config_id = 302 WHERE name = '服饰' AND is_system = true;
UPDATE categories SET config_id = 303 WHERE name = '数码产品' AND is_system = true;
UPDATE categories SET config_id = 304 WHERE name = '家居' AND is_system = true;
UPDATE categories SET config_id = 305 WHERE name = '美容' AND is_system = true;
UPDATE categories SET config_id = 4 WHERE name = '居住' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 401 WHERE name = '房租' AND is_system = true;
UPDATE categories SET config_id = 402 WHERE name = '水电煤气' AND is_system = true;
UPDATE categories SET config_id = 403 WHERE name = '物业费' AND is_system = true;
UPDATE categories SET config_id = 404 WHERE name = '网费' AND is_system = true;
UPDATE categories SET config_id = 405 WHERE name = '维修' AND is_system = true;
UPDATE categories SET config_id = 5 WHERE name = '娱乐' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 501 WHERE name = '电影' AND is_system = true;
UPDATE categories SET config_id = 502 WHERE name = '游戏' AND is_system = true;
UPDATE categories SET config_id = 503 WHERE name = 'KTV' AND is_system = true;
UPDATE categories SET config_id = 504 WHERE name = '运动' AND is_system = true;
UPDATE categories SET config_id = 505 WHERE name = '旅游' AND is_system = true;
UPDATE categories SET config_id = 6 WHERE name = '医疗' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 601 WHERE name = '药品' AND is_system = true;
UPDATE categories SET config_id = 602 WHERE name = '挂号' AND is_system = true;
UPDATE categories SET config_id = 603 WHERE name = '体检' AND is_system = true;
UPDATE categories SET config_id = 604 WHERE name = '保健品' AND is_system = true;
UPDATE categories SET config_id = 605 WHERE name = '保险' AND is_system = true;
UPDATE categories SET config_id = 7 WHERE name = '教育' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 701 WHERE name = '学费' AND is_system = true;
UPDATE categories SET config_id = 702 WHERE name = '书籍' AND is_system = true;
UPDATE categories SET config_id = 703 WHERE name = '培训' AND is_system = true;
UPDATE categories SET config_id = 704 WHERE name = '在线课程' AND is_system = true;
UPDATE categories SET config_id = 705 WHERE name = '考试' AND is_system = true;
UPDATE categories SET config_id = 8 WHERE name = '通讯' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 801 WHERE name = '话费' AND is_system = true;
UPDATE categories SET config_id = 802 WHERE name = '流量' AND is_system = true;
UPDATE categories SET config_id = 803 WHERE name = '宽带' AND is_system = true;
UPDATE categories SET config_id = 804 WHERE name = '邮寄' AND is_system = true;
UPDATE categories SET config_id = 9 WHERE name = '人情' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 901 WHERE name = '红包' AND is_system = true;
UPDATE categories SET config_id = 902 WHERE name = '请客' AND is_system = true;
UPDATE categories SET config_id = 903 WHERE name = '礼品' AND is_system = true;
UPDATE categories SET config_id = 904 WHERE name = '孝敬' AND is_system = true;
UPDATE categories SET config_id = 10 WHERE name = '其他支出' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 1001 WHERE name = '工资' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 10001 WHERE name = '基本工资' AND is_system = true;
UPDATE categories SET config_id = 10002 WHERE name = '绩效奖金' AND is_system = true;
UPDATE categories SET config_id = 10003 WHERE name = '补贴' AND is_system = true;
UPDATE categories SET config_id = 1002 WHERE name = '奖金' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 10011 WHERE name = '年终奖' AND is_system = true;
UPDATE categories SET config_id = 10012 WHERE name = '项目奖金' AND is_system = true;
UPDATE categories SET config_id = 10013 WHERE name = '提成' AND is_system = true;
UPDATE categories SET config_id = 1003 WHERE name = '投资收益' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 10021 WHERE name = '股票' AND is_system = true;
UPDATE categories SET config_id = 10022 WHERE name = '基金' AND is_system = true;
UPDATE categories SET config_id = 10023 WHERE name = '利息' AND is_system = true;
UPDATE categories SET config_id = 10024 WHERE name = '数字货币' AND is_system = true;
UPDATE categories SET config_id = 1004 WHERE name = '兼职' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 10031 WHERE name = '外包' AND is_system = true;
UPDATE categories SET config_id = 10032 WHERE name = '打零工' AND is_system = true;
UPDATE categories SET config_id = 10033 WHERE name = '咨询' AND is_system = true;
UPDATE categories SET config_id = 1005 WHERE name = '礼金' AND parent_id IS NULL AND is_system = true;
UPDATE categories SET config_id = 10041 WHERE name = '生日礼金' AND is_system = true;
UPDATE categories SET config_id = 10042 WHERE name = '节日礼金' AND is_system = true;
UPDATE categories SET config_id = 10043 WHERE name = '婚礼礼金' AND is_system = true;
UPDATE categories SET config_id = 1006 WHERE name = '其他收入' AND parent_id IS NULL AND is_system = true;
