/**
 * 图标分类数据 - 共享常量
 *
 * 用于：
 * - Categories.tsx (分类管理页面)
 * - Transactions.tsx (记账页面)
 *
 * 修改此文件会同时影响两个页面的图标选择器
 */

export interface IconCategory {
  name: string;
  icons: Array<{ code: string; name: string }>;
}

/**
 * Material Icon 图标分类
 *
 * 设计原则：
 * - 只保留具体的、可记录的消费项目
 * - 移除抽象概念、工具、功能类图标
 * - 避免重复和冗余
 */
export const MATERIAL_ICON_CATEGORIES: IconCategory[] = [
  {
    name: '餐饮',
    icons: [
      // 用餐时间
      { code: 'breakfast_dining', name: '早餐' },
      { code: 'brunch_dining', name: '早午餐' },
      { code: 'lunch_dining', name: '午餐' },
      { code: 'dinner_dining', name: '晚餐' },
      // 餐厅类型
      { code: 'restaurant', name: '餐厅' },
      { code: 'local_restaurant', name: '本地餐厅' },
      { code: 'table_restaurant', name: '餐桌' },
      { code: 'fastfood', name: '快餐' },
      { code: 'dining', name: '餐饮' },
      // 餐饮服务
      { code: 'takeout_dining', name: '外卖' },
      { code: 'delivery_dining', name: '外送' },
      { code: 'set_meal', name: '套餐' },
      { code: 'free_breakfast', name: '免费早餐' },
      { code: 'restaurant_menu', name: '菜单' },
      { code: 'food_bank', name: '食物银行' },
      // 特色餐饮
      { code: 'ramen_dining', name: '拉面' },
      { code: 'rice_bowl', name: '米饭' },
      { code: 'kebab_dining', name: '烤肉串' },
      { code: 'local_pizza', name: '披萨' },
      { code: 'tapas', name: '塔帕斯' },
      { code: 'outdoor_grill', name: '烧烤' },
      // 食物
      { code: 'soup_kitchen', name: '汤' },
      { code: 'bakery_dining', name: '烘焙' },
      { code: 'cookie', name: '曲奇' },
      { code: 'cake', name: '蛋糕' },
      { code: 'egg', name: '鸡蛋' },
      { code: 'icecream', name: '冰淇淋' },
      { code: 'flatware', name: '餐具' },
      { code: 'emoji_food_beverage', name: '食物饮料' },
      // 饮料
      { code: 'local_cafe', name: '咖啡馆' },
      { code: 'coffee', name: '咖啡' },
      { code: 'coffee_maker', name: '咖啡机' },
      { code: 'local_drink', name: '饮料' },
      { code: 'local_bar', name: '酒吧' },
      { code: 'liquor', name: '烈酒' },
      { code: 'wine_bar', name: '红酒' },
      { code: 'sports_bar', name: '运动酒吧' },
      { code: 'water', name: '水' },
      { code: 'water_drop', name: '水滴' },
    ],
  },
  {
    name: '交通',
    icons: [
      { code: 'directions', name: '导航' },
      { code: 'directions_bus', name: '公交' },
      { code: 'directions_bike', name: '共享单车' },
      { code: 'directions_boat', name: '船只' },
      { code: 'directions_car', name: '私家车' },
      { code: 'directions_ferry', name: '轮渡' },
      { code: 'directions_railway', name: '轻轨' },
      { code: 'directions_run', name: '步行导航' },
      { code: 'directions_subway', name: '地铁' },
      { code: 'directions_transit', name: '公共交通' },
      { code: 'directions_walk', name: '步行' },
      { code: 'flight', name: '飞机' },
      { code: 'flight_land', name: '降落' },
      { code: 'flight_takeoff', name: '起飞' },
      { code: 'local_airport', name: '机场' },
      { code: 'local_car_wash', name: '洗车' },
      { code: 'local_gas_station', name: '加油' },
      { code: 'local_parking', name: '停车费' },
      { code: 'local_taxi', name: '打车' },
      { code: 'traffic', name: '交通路况' },
      { code: 'subway', name: '地铁' },
      { code: 'train', name: '火车' },
      { code: 'build', name: '保养' },
      { code: 'no_crash', name: '保险' },
      { code: 'car_rental', name: '租车' },
      { code: 'ev_station', name: '充电' },
    ],
  },
  {
    name: '购物',
    icons: [
      { code: 'checkroom', name: '服饰' },
      { code: 'devices', name: '数码产品' },
      { code: 'soap', name: '日用品' },
      { code: 'weekend', name: '家居' },
      { code: 'local_florist', name: '鲜花' },
      { code: 'child_care', name: '玩具' },
      { code: 'book', name: '图书' },
      { code: 'fitness_center', name: '运动用品' },
      { code: 'local_laundry_service', name: '洗衣' },
      { code: 'shopping_cart', name: '购物车' },
      { code: 'shopping_basket', name: '购物篮' },
      { code: 'add_shopping_cart', name: '添加购物' },
      { code: 'store', name: '商店' },
      { code: 'local_mall', name: '商场' },
      { code: 'local_grocery_store', name: '超市' },
      { code: 'local_convenience_store', name: '便利店' },
      { code: 'computer', name: '电脑' },
      { code: 'laptop', name: '笔记本' },
      { code: 'smartphone', name: '手机' },
      { code: 'phone', name: '电话' },
      { code: 'camera', name: '相机' },
      { code: 'watch', name: '手表' },
      { code: 'toys', name: '玩具' },
      { code: 'card_giftcard', name: '礼品卡' },
      { code: 'redeem', name: '兑换' },
    ],
  },
  {
    name: '住房',
    icons: [
      { code: 'home', name: '房租' },
      { code: 'home_work', name: '房贷' },
      { code: 'payments', name: '物业费' },
      { code: 'water_drop', name: '水费' },
      { code: 'electrical_services', name: '电费' },
      { code: 'local_fire_department', name: '燃气费' },
      { code: 'router', name: '网费' },
      { code: 'waves', name: '供暖费' },
      { code: 'cleaning_services', name: '家政' },
      { code: 'handyman', name: '维修' },
      { code: 'room', name: '房间' },
      { code: 'hotel', name: '酒店' },
      { code: 'kitchen', name: '厨房' },
      { code: 'pool', name: '游泳池' },
      { code: 'spa', name: '温泉' },
      { code: 'room_service', name: '客房服务' },
      { code: 'account_balance', name: '账户余额' },
      { code: 'account_balance_wallet', name: '钱包余额' },
      { code: 'payment', name: '支付' },
      { code: 'receipt', name: '收据' },
      { code: 'attach_money', name: '附加金额' },
      { code: 'money_off', name: '金额减免' },
      { code: 'alarm', name: '闹钟' },
      { code: 'alarm_add', name: '添加闹钟' },
      { code: 'alarm_on', name: '闹钟开启' },
      { code: 'alarm_off', name: '闹钟关闭' },
      { code: 'lock', name: '锁' },
      { code: 'lock_open', name: '开锁' },
      { code: 'lock_outline', name: '锁轮廓' },
      { code: 'lightbulb_outline', name: '灯泡' },
      { code: 'storage', name: '存储' },
      { code: 'security', name: '安全' },
      { code: 'wifi', name: 'WiFi' },
      { code: 'wifi_lock', name: 'WiFi锁' },
      { code: 'wifi_tethering', name: 'WiFi热点' },
    ],
  },
  {
    name: '订阅',
    icons: [
      { code: 'play_circle', name: '视频会员' },
      { code: 'apps', name: '软件服务' },
      { code: 'videogame_asset', name: '游戏' },
      { code: 'menu_book', name: '知识付费' },
      { code: 'cloud', name: '云存储' },
      { code: 'star', name: '星级会员' },
      { code: 'workspace_premium', name: 'VIP' },
      { code: 'verified', name: '认证会员' },
      { code: 'card_membership', name: '会员卡' },
      { code: 'subscriptions', name: '订阅' },
      { code: 'stars', name: '收藏' },
      { code: 'star_border', name: '未收藏' },
      { code: 'star_half', name: '半星' },
      { code: 'star_rate', name: '评分' },
      { code: 'cloud_download', name: '云下载' },
      { code: 'cloud_upload', name: '云上传' },
      { code: 'cloud_done', name: '云完成' },
      { code: 'cloud_off', name: '云离线' },
      { code: 'cloud_queue', name: '云队列' },
      { code: 'cloud_circle', name: '云圈' },
      { code: 'games', name: '游戏' },
      { code: 'gamepad', name: '手柄' },
      { code: 'music_note', name: '音乐' },
      { code: 'library_music', name: '音乐库' },
      { code: 'music_video', name: '音乐视频' },
      { code: 'queue_music', name: '播放队列' },
      { code: 'video_library', name: '视频库' },
      { code: 'videocam', name: '摄像头' },
      { code: 'ondemand_video', name: '点播' },
      { code: 'personal_video', name: '个人视频' },
    ],
  },
  {
    name: '娱乐',
    icons: [
      { code: 'sports_esports', name: '游戏' },
      { code: 'movie', name: '电影' },
      { code: 'mic', name: 'KTV' },
      { code: 'landscape', name: '景点' },
      { code: 'theater_comedy', name: '演出' },
      { code: 'photo_camera', name: '摄影' },
      { code: 'sports', name: '运动' },
      { code: 'theaters', name: '影院' },
      { code: 'music_note', name: '音乐' },
      { code: 'music_video', name: '音乐视频' },
      { code: 'album', name: '专辑' },
      { code: 'games', name: '游戏' },
      { code: 'gamepad', name: '手柄' },
      { code: 'videogame_asset', name: '电子游戏' },
      { code: 'event', name: '活动' },
      { code: 'event_seat', name: '座位' },
      { code: 'play_arrow', name: '播放' },
      { code: 'play_circle_filled', name: '播放圆圈' },
      { code: 'play_circle_outline', name: '播放圆圈边框' },
      { code: 'video_library', name: '视频库' },
      { code: 'videocam', name: '摄像头' },
      { code: 'speaker', name: '扬声器' },
      { code: 'speaker_group', name: '扬声器组' },
      { code: 'headset_mic', name: '耳机麦克风' },
      { code: 'tv', name: '电视' },
      { code: 'camera', name: '相机' },
      { code: 'camera_alt', name: '相机切换' },
      { code: 'photo', name: '照片' },
      { code: 'photo_album', name: '相册' },
      { code: 'photo_library', name: '照片库' },
      { code: 'slideshow', name: '幻灯片' },
      { code: 'local_movies', name: '本地电影' },
      { code: 'live_tv', name: '直播电视' },
      { code: 'ondemand_video', name: '点播视频' },
      { code: 'personal_video', name: '个人视频' },
      { code: 'party_mode', name: '派对' },
    ],
  },
  {
    name: '健康',
    icons: [
      { code: 'assignment', name: '体检' },
      { code: 'medication', name: '药品' },
      { code: 'local_hospital', name: '医院' },
      { code: 'event_available', name: '挂号' },
      { code: 'vaccines', name: '保健品' },
      { code: 'verified_user', name: '保险' },
      { code: 'fitness_center', name: '健身' },
      { code: 'spa', name: '按摩' },
      { code: 'healing', name: '治疗' },
      { code: 'local_pharmacy', name: '药房' },
    ],
  },
  {
    name: '教育',
    icons: [
      { code: 'school', name: '学费' },
      { code: 'menu_book', name: '书籍' },
      { code: 'cast_for_education', name: '培训' },
      { code: 'computer', name: '在线课程' },
      { code: 'quiz', name: '考试' },
      { code: 'book', name: '图书' },
      { code: 'class', name: '课程' },
      { code: 'grade', name: '评分' },
      { code: 'history', name: '历史' },
      { code: 'local_library', name: '图书馆' },
      { code: 'library_books', name: '藏书' },
      { code: 'library_add', name: '添加书籍' },
      { code: 'collections_bookmark', name: '书签' },
      { code: 'bookmark', name: '收藏' },
      { code: 'bookmark_border', name: '未收藏' },
      { code: 'chrome_reader_mode', name: '阅读模式' },
      { code: 'art_track', name: '艺术' },
    ],
  },
  {
    name: '人情',
    icons: [
      { code: 'card_giftcard', name: '红包' },
      { code: 'restaurant_menu', name: '请客' },
      { code: 'redeem', name: '礼品' },
      { code: 'elderly', name: '孝敬' },
      { code: 'volunteer_activism', name: '借出' },
      { code: 'celebration', name: '庆典' },
      { code: 'favorite', name: '收藏' },
      { code: 'favorite_border', name: '未收藏' },
      { code: 'help', name: '帮助' },
      { code: 'help_outline', name: '帮助轮廓' },
      { code: 'live_help', name: '在线帮助' },
      { code: 'child_care', name: '儿童' },
      { code: 'child_friendly', name: '儿童友好' },
      { code: 'party_mode', name: '派对' },
      { code: 'people', name: '人群' },
      { code: 'people_outline', name: '人群轮廓' },
      { code: 'person', name: '个人' },
      { code: 'person_add', name: '添加好友' },
      { code: 'share', name: '分享' },
    ],
  },
  {
    name: '其他',
    icons: [
      { code: 'phone_in_talk', name: '话费' },
      { code: 'pets', name: '宠物' },
      { code: 'account_balance_wallet', name: '钱包' },
      { code: 'card_giftcard', name: '礼品卡' },
      { code: 'card_membership', name: '会员卡' },
      { code: 'credit_card', name: '信用卡' },
      { code: 'payment', name: '支付' },
      { code: 'receipt', name: '收据' },
      { code: 'call', name: '通话' },
      { code: 'chat', name: '聊天' },
      { code: 'chat_bubble', name: '聊天气泡' },
      { code: 'chat_bubble_outline', name: '聊天气泡边框' },
      { code: 'contact_mail', name: '邮件联系' },
      { code: 'contact_phone', name: '电话联系' },
      { code: 'email', name: '邮件' },
      { code: 'mail_outline', name: '邮件轮廓' },
      { code: 'message', name: '短信' },
      { code: 'phone', name: '电话' },
      { code: 'textsms', name: '文本短信' },
      { code: 'voicemail', name: '语音信箱' },
      { code: 'mail', name: '信件' },
      { code: 'storage', name: '存储' },
      { code: 'sd_storage', name: 'SD卡存储' },
      { code: 'attach_money', name: '附加金额' },
      { code: 'money_off', name: '金额减免' },
    ],
  },
];

/**
 * 预设颜色
 */
export const COLOR_PRESETS = [
  '#F5222D', '#FA8C16', '#FAAD14', '#52C41A', '#13C2C2',
  '#1890FF', '#722ED1', '#EB2F96',
];
