version: '1.0'
name: backend-build
displayName: BackendBuild
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
    paths:
      include:
        - backend/**
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    steps:
      - step: build@gradle
        name: build_gradle
        displayName: Gradle 构建
        jdkVersion: '17'
        gradleVersion: '8.8'
        commands:
          - '# Gradle默认构建命令'
          - cd backend
          - chmod +x ./gradlew
          - ./gradlew bootJar
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        caches:
          - ~/.gradle/caches
        notify: []
        strategy:
          retry: '0'
  - name: stage-c2a81d72
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
