version: '1.0'
name: alfred-master
displayName: Alfred 主分支构建

triggers:
  push:
    include:
      - master

stages:
  - name: build
    displayName: 构建
    jobs:
      - name: backend-build
        displayName: 后端构建
        runner:
          env: pipeline
        steps:
          - name: 检出代码
            run: |
              git clone --branch=$CI_COMMIT_REF_NAME https://gitee.com/$CI_REPO_SLUG.git .
              git log -1

          - name: 安装JDK
            run: |
                apt-get update
                apt-get install -y openjdk-17-jdk
                export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                java -version

          - name: 构建jar包
            run: |
              cd backend
              chmod +x gradlew
              ./gradlew bootJar --no-daemon
            timeout: 600

          - name: 上传构建产物
            run: |
              mkdir -p $CI_ARTIFACT_PATH
              cp backend/build/libs/app.jar $CI_ARTIFACT_PATH/

      - name: frontend-build
        displayName: 前端构建
        runner:
          env: pipeline
        steps:
          - name: 检出代码
            run: |
              git clone --branch=$CI_COMMIT_REF_NAME https://gitee.com/$CI_REPO_SLUG.git .
              git log -1

          - name: 安装Node.js
            run: |
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt-get install -y nodejs

          - name: 安装依赖并构建
            run: |
              cd frontend
              npm install
              npm run build
            timeout: 600

          - name: 打包构建产物
            run: |
              mkdir -p $CI_ARTIFACT_PATH
              cd frontend/dist
              tar czf $CI_ARTIFACT_PATH/dist.tar.gz .
